version: '3.8'

services:
  django:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    command: >
      sh -c "sleep 1 && 
             python manage.py migrate &&
             python manage.py loaddata example_db_data.json &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: pg_kitty
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
volumes:
  pg_data:
