# Generated by Django 5.1.1 on 2024-10-01 13:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KittyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Рейтинг')),
                ('kitty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='cats.kitty')),
            ],
        ),
    ]
